// Generated by gencpp from file sentry_userdefinition/QueryGlobalLocalization.msg
// DO NOT EDIT!


#ifndef SENTRY_USERDEFINITION_MESSAGE_QUERYGLOBALLOCALIZATION_H
#define SENTRY_USERDEFINITION_MESSAGE_QUERYGLOBALLOCALIZATION_H

#include <ros/service_traits.h>


#include <sentry_userdefinition/QueryGlobalLocalizationRequest.h>
#include <sentry_userdefinition/QueryGlobalLocalizationResponse.h>


namespace sentry_userdefinition
{

struct QueryGlobalLocalization
{

typedef QueryGlobalLocalizationRequest Request;
typedef QueryGlobalLocalizationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct QueryGlobalLocalization
} // namespace sentry_userdefinition


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sentry_userdefinition::QueryGlobalLocalization > {
  static const char* value()
  {
    return "2e563a5d7af1f98cbac55cf8c1e0a1ba";
  }

  static const char* value(const ::sentry_userdefinition::QueryGlobalLocalization&) { return value(); }
};

template<>
struct DataType< ::sentry_userdefinition::QueryGlobalLocalization > {
  static const char* value()
  {
    return "sentry_userdefinition/QueryGlobalLocalization";
  }

  static const char* value(const ::sentry_userdefinition::QueryGlobalLocalization&) { return value(); }
};


// service_traits::MD5Sum< ::sentry_userdefinition::QueryGlobalLocalizationRequest> should match
// service_traits::MD5Sum< ::sentry_userdefinition::QueryGlobalLocalization >
template<>
struct MD5Sum< ::sentry_userdefinition::QueryGlobalLocalizationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sentry_userdefinition::QueryGlobalLocalization >::value();
  }
  static const char* value(const ::sentry_userdefinition::QueryGlobalLocalizationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sentry_userdefinition::QueryGlobalLocalizationRequest> should match
// service_traits::DataType< ::sentry_userdefinition::QueryGlobalLocalization >
template<>
struct DataType< ::sentry_userdefinition::QueryGlobalLocalizationRequest>
{
  static const char* value()
  {
    return DataType< ::sentry_userdefinition::QueryGlobalLocalization >::value();
  }
  static const char* value(const ::sentry_userdefinition::QueryGlobalLocalizationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sentry_userdefinition::QueryGlobalLocalizationResponse> should match
// service_traits::MD5Sum< ::sentry_userdefinition::QueryGlobalLocalization >
template<>
struct MD5Sum< ::sentry_userdefinition::QueryGlobalLocalizationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sentry_userdefinition::QueryGlobalLocalization >::value();
  }
  static const char* value(const ::sentry_userdefinition::QueryGlobalLocalizationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sentry_userdefinition::QueryGlobalLocalizationResponse> should match
// service_traits::DataType< ::sentry_userdefinition::QueryGlobalLocalization >
template<>
struct DataType< ::sentry_userdefinition::QueryGlobalLocalizationResponse>
{
  static const char* value()
  {
    return DataType< ::sentry_userdefinition::QueryGlobalLocalization >::value();
  }
  static const char* value(const ::sentry_userdefinition::QueryGlobalLocalizationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SENTRY_USERDEFINITION_MESSAGE_QUERYGLOBALLOCALIZATION_H
