// Generated by gencpp from file sentry_userdefinition/SetGlobalLocalizationEngine.msg
// DO NOT EDIT!


#ifndef SENTRY_USERDEFINITION_MESSAGE_SETGLOBALLOCALIZATIONENGINE_H
#define SENTRY_USERDEFINITION_MESSAGE_SETGLOBALLOCALIZATIONENGINE_H

#include <ros/service_traits.h>


#include <sentry_userdefinition/SetGlobalLocalizationEngineRequest.h>
#include <sentry_userdefinition/SetGlobalLocalizationEngineResponse.h>


namespace sentry_userdefinition
{

struct SetGlobalLocalizationEngine
{

typedef SetGlobalLocalizationEngineRequest Request;
typedef SetGlobalLocalizationEngineResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetGlobalLocalizationEngine
} // namespace sentry_userdefinition


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sentry_userdefinition::SetGlobalLocalizationEngine > {
  static const char* value()
  {
    return "f71639c3aeb058fa00da5a20981c23c9";
  }

  static const char* value(const ::sentry_userdefinition::SetGlobalLocalizationEngine&) { return value(); }
};

template<>
struct DataType< ::sentry_userdefinition::SetGlobalLocalizationEngine > {
  static const char* value()
  {
    return "sentry_userdefinition/SetGlobalLocalizationEngine";
  }

  static const char* value(const ::sentry_userdefinition::SetGlobalLocalizationEngine&) { return value(); }
};


// service_traits::MD5Sum< ::sentry_userdefinition::SetGlobalLocalizationEngineRequest> should match
// service_traits::MD5Sum< ::sentry_userdefinition::SetGlobalLocalizationEngine >
template<>
struct MD5Sum< ::sentry_userdefinition::SetGlobalLocalizationEngineRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sentry_userdefinition::SetGlobalLocalizationEngine >::value();
  }
  static const char* value(const ::sentry_userdefinition::SetGlobalLocalizationEngineRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sentry_userdefinition::SetGlobalLocalizationEngineRequest> should match
// service_traits::DataType< ::sentry_userdefinition::SetGlobalLocalizationEngine >
template<>
struct DataType< ::sentry_userdefinition::SetGlobalLocalizationEngineRequest>
{
  static const char* value()
  {
    return DataType< ::sentry_userdefinition::SetGlobalLocalizationEngine >::value();
  }
  static const char* value(const ::sentry_userdefinition::SetGlobalLocalizationEngineRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sentry_userdefinition::SetGlobalLocalizationEngineResponse> should match
// service_traits::MD5Sum< ::sentry_userdefinition::SetGlobalLocalizationEngine >
template<>
struct MD5Sum< ::sentry_userdefinition::SetGlobalLocalizationEngineResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sentry_userdefinition::SetGlobalLocalizationEngine >::value();
  }
  static const char* value(const ::sentry_userdefinition::SetGlobalLocalizationEngineResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sentry_userdefinition::SetGlobalLocalizationEngineResponse> should match
// service_traits::DataType< ::sentry_userdefinition::SetGlobalLocalizationEngine >
template<>
struct DataType< ::sentry_userdefinition::SetGlobalLocalizationEngineResponse>
{
  static const char* value()
  {
    return DataType< ::sentry_userdefinition::SetGlobalLocalizationEngine >::value();
  }
  static const char* value(const ::sentry_userdefinition::SetGlobalLocalizationEngineResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SENTRY_USERDEFINITION_MESSAGE_SETGLOBALLOCALIZATIONENGINE_H
