// Generated by gencpp from file sentry_userdefinition/SetGlobalMap.msg
// DO NOT EDIT!


#ifndef SENTRY_USERDEFINITION_MESSAGE_SETGLOBALMAP_H
#define SENTRY_USERDEFINITION_MESSAGE_SETGLOBALMAP_H

#include <ros/service_traits.h>


#include <sentry_userdefinition/SetGlobalMapRequest.h>
#include <sentry_userdefinition/SetGlobalMapResponse.h>


namespace sentry_userdefinition
{

struct SetGlobalMap
{

typedef SetGlobalMapRequest Request;
typedef SetGlobalMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetGlobalMap
} // namespace sentry_userdefinition


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sentry_userdefinition::SetGlobalMap > {
  static const char* value()
  {
    return "5ed403eb1abbaa077410b645f248da4e";
  }

  static const char* value(const ::sentry_userdefinition::SetGlobalMap&) { return value(); }
};

template<>
struct DataType< ::sentry_userdefinition::SetGlobalMap > {
  static const char* value()
  {
    return "sentry_userdefinition/SetGlobalMap";
  }

  static const char* value(const ::sentry_userdefinition::SetGlobalMap&) { return value(); }
};


// service_traits::MD5Sum< ::sentry_userdefinition::SetGlobalMapRequest> should match
// service_traits::MD5Sum< ::sentry_userdefinition::SetGlobalMap >
template<>
struct MD5Sum< ::sentry_userdefinition::SetGlobalMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sentry_userdefinition::SetGlobalMap >::value();
  }
  static const char* value(const ::sentry_userdefinition::SetGlobalMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sentry_userdefinition::SetGlobalMapRequest> should match
// service_traits::DataType< ::sentry_userdefinition::SetGlobalMap >
template<>
struct DataType< ::sentry_userdefinition::SetGlobalMapRequest>
{
  static const char* value()
  {
    return DataType< ::sentry_userdefinition::SetGlobalMap >::value();
  }
  static const char* value(const ::sentry_userdefinition::SetGlobalMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sentry_userdefinition::SetGlobalMapResponse> should match
// service_traits::MD5Sum< ::sentry_userdefinition::SetGlobalMap >
template<>
struct MD5Sum< ::sentry_userdefinition::SetGlobalMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sentry_userdefinition::SetGlobalMap >::value();
  }
  static const char* value(const ::sentry_userdefinition::SetGlobalMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sentry_userdefinition::SetGlobalMapResponse> should match
// service_traits::DataType< ::sentry_userdefinition::SetGlobalMap >
template<>
struct DataType< ::sentry_userdefinition::SetGlobalMapResponse>
{
  static const char* value()
  {
    return DataType< ::sentry_userdefinition::SetGlobalMap >::value();
  }
  static const char* value(const ::sentry_userdefinition::SetGlobalMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SENTRY_USERDEFINITION_MESSAGE_SETGLOBALMAP_H
