// Generated by gencpp from file sentry_userdefinition/SetGlobalLocalizationEngineResponse.msg
// DO NOT EDIT!


#ifndef SENTRY_USERDEFINITION_MESSAGE_SETGLOBALLOCALIZATIONENGINERESPONSE_H
#define SENTRY_USERDEFINITION_MESSAGE_SETGLOBALLOCALIZATIONENGINERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sentry_userdefinition
{
template <class ContainerAllocator>
struct SetGlobalLocalizationEngineResponse_
{
  typedef SetGlobalLocalizationEngineResponse_<ContainerAllocator> Type;

  SetGlobalLocalizationEngineResponse_()
    {
    }
  SetGlobalLocalizationEngineResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::sentry_userdefinition::SetGlobalLocalizationEngineResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sentry_userdefinition::SetGlobalLocalizationEngineResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetGlobalLocalizationEngineResponse_

typedef ::sentry_userdefinition::SetGlobalLocalizationEngineResponse_<std::allocator<void> > SetGlobalLocalizationEngineResponse;

typedef boost::shared_ptr< ::sentry_userdefinition::SetGlobalLocalizationEngineResponse > SetGlobalLocalizationEngineResponsePtr;
typedef boost::shared_ptr< ::sentry_userdefinition::SetGlobalLocalizationEngineResponse const> SetGlobalLocalizationEngineResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sentry_userdefinition::SetGlobalLocalizationEngineResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sentry_userdefinition::SetGlobalLocalizationEngineResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace sentry_userdefinition

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sentry_userdefinition::SetGlobalLocalizationEngineResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sentry_userdefinition::SetGlobalLocalizationEngineResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sentry_userdefinition::SetGlobalLocalizationEngineResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sentry_userdefinition::SetGlobalLocalizationEngineResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sentry_userdefinition::SetGlobalLocalizationEngineResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sentry_userdefinition::SetGlobalLocalizationEngineResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sentry_userdefinition::SetGlobalLocalizationEngineResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::sentry_userdefinition::SetGlobalLocalizationEngineResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::sentry_userdefinition::SetGlobalLocalizationEngineResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sentry_userdefinition/SetGlobalLocalizationEngineResponse";
  }

  static const char* value(const ::sentry_userdefinition::SetGlobalLocalizationEngineResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sentry_userdefinition::SetGlobalLocalizationEngineResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::sentry_userdefinition::SetGlobalLocalizationEngineResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sentry_userdefinition::SetGlobalLocalizationEngineResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetGlobalLocalizationEngineResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sentry_userdefinition::SetGlobalLocalizationEngineResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::sentry_userdefinition::SetGlobalLocalizationEngineResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // SENTRY_USERDEFINITION_MESSAGE_SETGLOBALLOCALIZATIONENGINERESPONSE_H
