(cl:defpackage sentry_userdefinition-srv
  (:use )
  (:export
   "QUERYGLOBALLOCALIZATION"
   "<QUERYGLOBALLOCALIZATION-REQUEST>"
   "QUERYGLOBALLOCALIZATION-REQUEST"
   "<QUERYGLOBALLOCALIZATION-RESPONSE>"
   "QUERYGLOBALLOCALIZATION-RESPONSE"
   "SETGLOBALMAP"
   "<SETGLOBALMAP-REQUEST>"
   "SETGLOBALMAP-REQUEST"
   "<SETGLOBALMAP-RESPONSE>"
   "SETGLOBALMAP-RESPONSE"
  ))

